# Generated by Django 5.0.6 on 2024-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='predicted_category',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
