# Generated by Django 5.0.6 on 2024-06-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_predicted_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='predicted_category',
            new_name='category',
        ),
    ]
